// Generated by Wrangler by running `wrangler types`

export interface Env {
	AIBTCDEV_SERVICES_BUCKET: R2Bucket;
	AIBTCDEV_SERVICES_DB: D1Database;
	AIBTCDEV_SERVICES_KV: KVNamespace;
	AUTH_DO: DurableObjectNamespace<import('./src/index').AuthDO>;
	CDN_DO: DurableObjectNamespace<import('./src/index').CdnDO>;
	CONTEXT_DO: DurableObjectNamespace<import('./src/index').ContextDO>;
	DATABASE_DO: DurableObjectNamespace<import('./src/index').DatabaseDO>;
	SCHEDULER_DO: DurableObjectNamespace<import('./src/index').SchedulerDO>;
	TOOLS_DO: DurableObjectNamespace<import('./src/index').ToolsDO>;
	IMAGE_GENERATOR_DO: DurableObjectNamespace<import('./src/index').ImageGeneratorDO>;
	METADATA_GENERATOR_DO: DurableObjectNamespace<import('./src/index').MetadataGeneratorDO>;
	CDN_DO: DurableObjectNamespace<import('./src/index').CdnDO>;
	AIBTCDEV_SERVICES_BUCKET: R2Bucket;
	AIBTCDEV_SERVICES_DB: D1Database;
	OPENAI_API_KEY: string;
}
