name: Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Ship Ship Ship
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Test Endpoints (10s delay)
        run: |
          chmod +x tests/run_tests.sh
          ./tests/run_tests.sh https://cache.aibtc.dev true
